# Generated by Django 3.2.23 on 2023-12-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='dental_health',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breed',
            name='eyes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breed',
            name='general_condition',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breed',
            name='locomotor_system',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breed',
            name='other',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breed',
            name='skin_and_coat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed'),
        ),
    ]
