# Generated by Django 3.2.23 on 2024-04-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20231210_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='feed',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='insurance_company',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='insurance_number',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='pedigree_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='possible_feed_intolerance',
            field=models.TextField(default=None, null=True),
        ),
    ]
