# Generated by Django 3.2.23 on 2024-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='id_number',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='passport_number',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='registration_number',
            field=models.TextField(default=None, null=True),
        ),
    ]
