# Generated by Django 3.2.23 on 2024-07-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20240409_1634'),
    ]

    operations = [
    ]
