# Generated by Django 3.2.23 on 2024-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20240727_1336'),
    ]

    operations = [
    ]
