# Generated by Django 3.2.23 on 2024-06-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('strength', models.CharField(max_length=120)),
                ('administration_method', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=120)),
                ('administration_start_date', models.DateField()),
                ('administration_length', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vaccination_date', models.DateField()),
                ('next_vaccination_date', models.DateField(null=True)),
                ('clinic_name', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('onset_date', models.DateField()),
                ('follow_up_date', models.DateField()),
                ('vet_clinic', models.CharField(max_length=120, null=True)),
                ('notes', models.CharField(max_length=120)),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.medication')),
            ],
        ),
    ]
