# Generated by Django 3.2.23 on 2024-06-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20240409_1634'),
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='dog',
            field=models.ForeignKey(default='34', on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dog',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
            preserve_default=False,
        ),
    ]
