# Generated by Django 3.2.23 on 2024-06-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_auto_20240612_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='clinic_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='notes',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
