# Generated by Django 3.2.23 on 2024-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_alter_condition_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='notes',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
