# Generated by Django 3.2.23 on 2024-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_alter_condition_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='vet_clinic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
