# Generated by Django 3.2.23 on 2024-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_auto_20240617_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='healed',
            field=models.BooleanField(default=False),
        ),
    ]
