# Generated by Django 3.2.23 on 2024-06-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_condition_healed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.medication'),
        ),
    ]
