# Generated by Django 3.2.23 on 2024-07-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20240409_1634'),
        ('health_records', '0008_alter_condition_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='medication',
        ),
        migrations.AddField(
            model_name='medication',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.condition'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.dog'),
        ),
    ]
