# Generated by Django 3.2.23 on 2024-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0009_auto_20240701_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='vaccination_detailed_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
