# Generated by Django 3.2.23 on 2024-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
