# Generated by Django 3.2.23 on 2024-05-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0005_auto_20240409_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIndexBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthIndexQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=250)),
                ('responses', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DogHealthIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_run_batch_id', models.IntegerField(default=1)),
                ('date_performed', models.DateTimeField()),
                ('general_condition', models.IntegerField(default=1)),
                ('dental_health', models.IntegerField(default=1)),
                ('eyes', models.IntegerField(default=1)),
                ('skin_and_coat', models.IntegerField(default=1)),
                ('locomotor_system', models.IntegerField(default=1)),
                ('other', models.IntegerField(default=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
        ),
    ]
