# Generated by Django 3.2.23 on 2024-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doghealthindex',
            name='batches_in_row',
            field=models.IntegerField(default=0),
        ),
    ]
