# Generated by Django 3.2.23 on 2024-05-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_index', '0002_doghealthindex_batches_in_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthindexbatch',
            name='frequency',
            field=models.IntegerField(choices=[(1, '7/week'), (2, '3/week'), (3, 'Custom')], default=1),
        ),
    ]
