# Generated by Django 3.2.23 on 2024-08-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dog_image'),
        ('health_index', '0004_alter_doghealthindex_date_performed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toothbrushing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField()),
                ('streak', models.IntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
            ],
        ),
    ]
