# Generated by Django 3.2.23 on 2024-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_index', '0005_toothbrushing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toothbrushing',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
