# Generated by Django 3.2.23 on 2024-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_featured_article'),
        ('health_index', '0006_alter_toothbrushing_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthindexquestion',
            name='articles',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
    ]
