# Generated by Django 4.2.17 on 2025-02-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_index", "0007_healthindexquestion_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthindexquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("general_condition", "General Condition"),
                    ("dental_health", "Dental Health"),
                    ("eyes", "Eyes"),
                    ("skin_and_coat", "Skin and Coat"),
                    ("locomotor_system", "Locomotor System"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
