# Generated by Django 3.2.23 on 2024-02-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='testar', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
