# Generated by Django 3.2.23 on 2024-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_article',
            field=models.BooleanField(default=False),
        ),
    ]
